name: Deploy MkDocs to Garage
on:
  push:
    branches:
      - main  # Adjust to your branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install mkdocs-material

      - name: Build
        run: mkdocs build

      - name: Sync to Garage S3
        uses: https://github.com/jakejarvis/s3-sync-action@master
        with:
          args: --endpoint-url https://s3.garage.bouvais.lu --acl public-read --delete
        env:
          AWS_S3_BUCKET: 'zig-dimal.bouvais.lu'
          AWS_ACCESS_KEY_ID: ${{ secrets.GARAGE_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.GARAGE_SECRET_KEY }}
          AWS_REGION: 'garage' 
          SOURCE_DIR: 'site' # MkDocs defaults to 'site' folder for output
